// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © barandenizdogan

//@version=5
strategy("BB", overlay=true, currency = currency.USD, initial_capital=10, default_qty_type=strategy.cash, default_qty_value=100, commission_type = strategy.commission.cash_per_order, commission_value = 0.1)

// Define the inputs for the strategy
length = input.int(title="Length", defval=20)
k = input.float(title="Standard Deviation", defval=2)

// Calculate the Bollinger Bands
upperBand = ta.sma(close, length) + k * ta.stdev(close, length)
lowerBand = ta.sma(close, length) - k * ta.stdev(close, length)

// Buy when close price crosses above the upper Bollinger Band
if ta.crossover(close, upperBand)
    strategy.entry("Long", strategy.long)

// Sell when close price crosses below the lower Bollinger Band
if ta.crossunder(lowerBand, close)
    strategy.close("Long", comment = "Exit")

plot(upperBand, title = "Upper Band", color = color.green, linewidth = 1)
plot(lowerBand, title = "Lower Band", color = color.red, linewidth = 1)