// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © barandenizdogan

//@version=5
strategy("MACD", overlay=true, margin_long=100, margin_short=100)

fastLength = input(12, title="Fast Length")
slowLength = input(26, title="Slow Length")
signalLength = input(9, title="Signal Length")

fastMA = ta.ema(close, fastLength)
slowMA = ta.ema(close, slowLength)
macd = fastMA - slowMA
signal = ta.sma(macd, signalLength)
histogram = macd - signal

plot(macd, color=color.blue, title="MACD")
plot(signal, color=color.red, title="Signal")
plot(histogram, color=color.green, title="Histogram")